### ISSUE TITLE
Gatling endpoint synthesis

### ISSUE THREAD

**Issue by glandais** [ltoinel/IoT-Development-Challenge#13]
Dans le script Gatling https://github.com/ltoinel/IoT-Development-Challenge/blob/master/gatling/gatling_script.scala#L310 , on a pas le bon endpoint par rapport à ce qui est précisé dans le Swagger : https://github.com/ltoinel/IoT-Development-Challenge/blob/master/swagger/api-swagger.txt#L45

**Comment by IsBena** [comment]
le swagger a été mis à jour :)
