### ISSUE TITLE
java.text.SimpleDateFormat n'est pas thread safe

### ISSUE THREAD

**Issue by dpiraud** [ltoinel/IoT-Development-Challenge#26]
Le script gatling utilise une seule instance de java.text.SimpleDateFormat pour tous les threads.
Pendant l’exécution, en particulier pour la partie calcul des dates pour les demandes de synthèses intermédiaires, j'ai des effets de bord.
Sur mon poste, j'ai corrigé en créant une instance à chaque utilisation.

Doc:
https://docs.oracle.com/javase/7/docs/api/java/text/SimpleDateFormat.html
_Date formats are not synchronized. It is recommended to create separate format instances for each thread. If multiple threads access a format concurrently, it must be synchronized externally._

==>Confirmez-vous mon analyse? Si oui, je ne sais pas ce qui sera le plus propre: Instance par thread,  nouvelle instance à chaque utilisation, bloque synchronisé...

**Comment by IsBena** [comment]
depuis mes recherche je vois qu'il y a un problème avec date format et multithreading je pense que la solution la plus simple est d’appeler un new formatter dans chaque thread , cela se fera sur le ScenarioBuilder

**Comment by glandais** [comment]
Le [DateTimeFormatter](https://docs.oracle.com/javase/8/docs/api/java/time/format/DateTimeFormatter.html) de Java 8 est thread safe

> A formatter created from a pattern can be used as many times as necessary, it is immutable and is thread-safe.

**Comment by IsBena** [comment]
ok ! cela resoud le probleme alors! il faut que les candidat soit sur java 8 par contre ...

**Comment by glandais** [comment]
Le problème n'est pas résolu

**Comment by IsBena** [comment]
est ce que tu peux éclaircir le problème? tant que c'est threadsafe, est ce qu'il y a un autre problème avec le format de la date ?
