### ISSUE TITLE
Erreur de compilation

### ISSUE THREAD

**Issue by ghost** [ltoinel/IoT-Development-Challenge#28]
Impossible de lancer le script.

Voici les logs:
GATLING_HOME is set to /Users/anouar/Documents/gatling-charts-highcharts-bundle-2.2.0
20:44:39.563 [WARN ] i.g.c.ZincCompiler$ - Pruning sources from previous analysis, due to incompatible CompileSetup.
20:44:52.833 [WARN ] i.g.c.ZincCompiler$ - /Users/anouar/Documents/gatling-charts-highcharts-bundle-2.2.0/user-files/simulations/gatling_script.scala:381: non-variable type argument Map[String,Any] in type pattern List[Map[String,Any]](the underlying of List[Map[String,Any]]) is unchecked since it is eliminated by erasure
20:44:52.834 [WARN ] i.g.c.ZincCompiler$ -                  case Some(m: List[Map[String, Any]]) => (m(sensorTypeIndex))(synthesisValue) match{
20:44:52.836 [WARN ] i.g.c.ZincCompiler$ -                               ^
20:44:53.104 [ERROR] i.g.c.ZincCompiler$ - /Users/anouar/Documents/gatling-charts-highcharts-bundle-2.2.0/user-files/simulations/gatling_script.scala:399: value unary_+ is not a member of String
20:44:53.105 [ERROR] i.g.c.ZincCompiler$ -                      +java.net.URLEncoder.encode(formatter.format(simulationStartTime), "utf-8")
20:44:53.105 [ERROR] i.g.c.ZincCompiler$ -                      ^
20:44:53.108 [ERROR] i.g.c.ZincCompiler$ - /Users/anouar/Documents/gatling-charts-highcharts-bundle-2.2.0/user-files/simulations/gatling_script.scala:400: value unary_+ is not a member of String
20:44:53.108 [ERROR] i.g.c.ZincCompiler$ -                      +"&duration="+((timeOfSimulation/1000000000)+1).toInt
20:44:53.109 [ERROR] i.g.c.ZincCompiler$ -                      ^
20:44:53.119 [WARN ] i.g.c.ZincCompiler$ - one warning found
20:44:53.120 [ERROR] i.g.c.ZincCompiler$ - two errors found
20:44:53.125 [ERROR] i.g.c.ZincCompiler$ - Compilation crashed

Est ce qu'il faut utiliser une version spécifique? ou bien c'est vraiment le script qui ne compile pas?

**Comment by IsBena** [comment]
re-essaye avec le script recent ca marche, il y 'avait un probleme sur ces ligne et on a corriger : concat(""+((timeOfSimulation/1000000000)+1).toInt) envoi moi un message sur yammer si ca bloque encore !
