### ISSUE TITLE
Gatling baseURL

### ISSUE THREAD

**Issue by glandais** [ltoinel/IoT-Development-Challenge#7]
On devrait avoir
`
    val httpProtocol = http
        .baseURL("http://")
        .inferHtmlResources()
`
et non
`
    val httpProtocol = http
        .baseURL("http://gatling.io")
        .inferHtmlResources()
`

**Comment by ltoinel** [comment]
@IsBena : Peux-tu réaliser la correction ? Merci.

**Comment by IsBena** [comment]
c'est corrigé!
