### ISSUE TITLE
Gatling format date

### ISSUE THREAD

**Issue by glandais** [ltoinel/IoT-Development-Challenge#9]
Le format actuel du Gatling fournit une date comme `2016-04-27T09:26:50.247 +0000`
Je ne crois pas que cela soit conforme à la RFC3339, l'espace avant le + étant en trop (http://xml2rfc.ietf.org/public/rfc/html/rfc3339.html#anchor14)

**Comment by ltoinel** [comment]
@IsBena : Peux-tu réaliser la correction ? Merci.

**Comment by IsBena** [comment]
je me suis basé sur le RFC3339 officiel, j'ai enlevé l'espace et les doubles quotes pour le T.
